# GitHub Actions — Validate Python SDK
name: Validate Python SDK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.11"
            api_secret: REMOTERL_API_KEY_UBUNTU

          - os: windows-latest
            python-version: "3.11"
            api_secret: REMOTERL_API_KEY_WINDOWS

          - os: macos-latest
            python-version: "3.11"
            api_secret: REMOTERL_API_KEY_MACOS

    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    env:
      REMOTERL_API_KEY: ${{ secrets[matrix.api_secret] }}

    steps:
      # ────────────── Checkout ──────────────
      - uses: actions/checkout@v4

      # ────────────── System Python (pyenv) ──────────────
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # ────────────── Install deps & global env ──────────────
      - name: Install SDK & Stable-Baselines3
        shell: bash
        run: |
          set -euxo pipefail
          pip install --upgrade pip
          pip install --no-cache-dir \
              remoterl stable-baselines3

      # ────────────── Launch simulator (background) ──────────────
      - name: Launch a simulator
        shell: bash
        run: |
          set -euxo pipefail

          # ── Launch a single background simulator and remember its PID ──
          declare -a SIM_PIDS=()

          remoterl simulate --headless &      # start in background
          pid=$!                               # capture its PID
          SIM_PIDS+=("$pid")
          echo "Started simulator with PID=$pid"

          # Optional: brief pause so it finishes initialising
          sleep 10

      # ────────────── Train with Stable‑Baselines3 ──────────────
      - name: Train with Stable-Baselines3
        shell: bash
        run: |
          set -euxo pipefail
          remoterl train stable-baselines3 \
              --env_id CartPole-v1 --algo PPO \
              --total-timesteps 10000 \